// shared/components/AIDisclaimer.jsx
import React from 'react'
import { Info, AlertTriangle } from 'lucide-react'
import { Alert } from '@shared/components'

export const AIDisclaimer = ({ 
  variant = 'info',
  title = 'AI Analysis Notice',
  compact = false,
  className = '' 
}) => {
  const fullDisclaimer = (
    <Alert variant={variant} className={className}>
      <Info className="w-5 h-5 flex-shrink-0 mt-0.5" />
      <div className="text-sm">
        <p className="font-medium mb-1">{title}</p>
        <p>
          This AI analysis is for informational purposes only and does not represent a final decision. 
          All claims undergo manual review by authorized representatives before approval or rejection. 
          The AI system provides preliminary insights to assist in the claims process but should not 
          be considered as binding or definitive.
        </p>
      </div>
    </Alert>
  )

  const compactDisclaimer = (
    <div className={`text-xs text-gray-400 flex items-start gap-2 ${className}`}>
      <Info className="w-4 h-4 flex-shrink-0 mt-0.5" />
      <p>
        AI analysis is preliminary and non-binding. Final decisions are made by authorized representatives.
      </p>
    </div>
  )

  return compact ? compactDisclaimer : fullDisclaimer
}

export const FraudRiskDisclaimer = ({ className = '' }) => {
  return (
    <Alert variant="warning" className={className}>
      <AlertTriangle className="w-5 h-5 flex-shrink-0 mt-0.5" />
      <div className="text-sm">
        <p className="font-medium mb-1">Risk Assessment Notice</p>
        <p>
          The fraud risk indicators shown are generated by AI analysis and are intended to highlight 
          potential areas for review. These indicators do not constitute accusations of fraud and 
          should be considered as part of a comprehensive review process.
        </p>
      </div>
    </Alert>
  )
}

export const ProcessingDisclaimer = ({ className = '' }) => {
  return (
    <div className={`bg-blue-500/10 border border-blue-500/30 rounded-lg p-4 ${className}`}>
      <div className="flex items-start gap-3">
        <div className="p-2 bg-blue-500/20 rounded-lg">
          <Info className="w-5 h-5 text-blue-400" />
        </div>
        <div className="flex-1">
          <h4 className="font-medium text-white mb-1">How AI Processing Works</h4>
          <ul className="text-sm text-gray-300 space-y-1">
            <li>• Documents are analyzed to extract relevant information</li>
            <li>• Extracted data is used to pre-fill your claim form</li>
            <li>• You can review and edit all information before submission</li>
            <li>• AI suggestions help identify potential issues early</li>
          </ul>
        </div>
      </div>
    </div>
  )
}

export default AIDisclaimer